name: Build APK
on:
  push:
    branches:
      - main # 可根据实际情况修改为其他分支
jobs:
  build:
    runs-on: ubuntu - latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup - java@v2
        with:
          java - version: 11 # 可根据项目需求调整JDK版本
      - name: Build APK
        run:./gradlew assembleDebug
