name: Auto Build Debug APK

on:
  workflow_dispatch:   # 手动触发
  push:                # 代码推送时自动触发
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ------ 代码检出 ------
    - name: Checkout code
      uses: actions/checkout@v4

    # ------ 环境配置 ------
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: "34.0.0"  # 与项目build.gradle一致
        platform-version: "android-34"  # 与compileSdkVersion一致

    # ------ 构建优化 ------
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    # ------ 必要预处理 ------
    - name: Fix Gradle Permissions
      run: chmod +x gradlew

    - name: Accept SDK Licenses
      run: yes | sdkmanager --licenses

    # ------ 构建任务 ------
    - name: Build Debug APK
      run: ./gradlew assembleDebug --parallel

    # ------ 产物处理 ------
    - name: Collect APKs
      run: |
        mkdir -p apk_output
        find . -path "*/build/outputs/apk/debug/*.apk" -exec cp {} apk_output \;

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: apk_output/*.apk

    - name: Upload Release APK
      if: ${{ secrets.KEYSTORE_FILE }}
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
