name: Android Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ------ 代码检出 ------
    - uses: actions/checkout@v4  # 升级到最新版
      with:
        fetch-depth: 0

    # ------ 环境配置 ------
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: "34.0.0"  # 与项目配置一致
        platform-version: "android-34"  # 与compileSdkVersion一致

    # ------ 构建优化 ------
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

    # ------ 必要预处理 ------
    - name: Grant execute permission
      run: chmod +x gradlew

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    # ------ 构建任务 ------
    - name: Build Release APK
      run: |
        ./gradlew assembleRelease \
          --build-cache \
          --parallel \
          --warning-mode all

    # ------ 精准收集APK ------
    - name: Collect APKs
      run: |
        APK_DIR="${{ github.workspace }}/apk"
        mkdir -p "$APK_DIR"
        # 精确匹配标准输出路径
        find . -path "*/build/outputs/apk/*release/*.apk" -exec cp {} "$APK_DIR" \;

    # ------ 上传结果 ------
    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 升级到最新版
      with:
        name: release-apk-package
        path: ${{ github.workspace }}/apk/*.apk
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    # ------ 必要预处理 ------
    - name: Fix Gradle Permissions
      run: chmod +x gradlew  # 单行命令无需管道符

    - name: Accept SDK Licenses
      run: yes | sdkmanager --licenses

    # ------ 构建任务 ------
    - name: Build Debug APK
      run: ./gradlew assembleDebug --parallel

    # ------ 正确缩进的多行命令示例 ------
    - name: Collect APKs
      run: |  # ✅ 正确缩进（前面两个空格）
        mkdir -p apk_output
        find . -path "*/build/outputs/apk/debug/*.apk" -exec cp {} apk_output \;

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: apk_output/*.apk
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    # ------ 必要预处理 ------
    - name: Fix Gradle Permissions
      run: chmod +x gradlew

    - name: Accept SDK Licenses
      run: yes | sdkmanager --licenses

    # ------ 构建任务 ------
    - name: Build Debug APK
      run: ./gradlew assembleDebug --parallel

    # ------ 产物处理 ------
    - name: Collect APKs
      run: |
        mkdir -p apk_output
        find . -path "*/build/outputs/apk/debug/*.apk" -exec cp {} apk_output \;

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: apk_output/*.apk

    - name: Upload Release APK
      if: ${{ secrets.KEYSTORE_FILE }}
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
